src/foam/u2/view/ScrollTableView.js, src/foam/u2/view/TableView.js
fixing only scrolling as of now
=> fixes scrolling

src/foam/nanos/auth/StandardAuthorizer.java, src/foam/test/TestUtils.java, src/foam/util/Auth.java
Looking through previously written tests, noticed incorrect and duplicate code being written to support the auth logic in testing environments. 
Added some testing utility methods to help make test setup easier and proper.
Further documentation explaining each methods use is defined above its declaration.
=> Additional Test Utility methods

src/foam/nanos/auth/email/EmailVerificationWebAgent.js
address: https://nanopay.atlassian.net/browse/NP-4028
nanoside: https://github.com/nanoPayinc/NANOPAY/pull/12324
=> using logoImage instead of logo

src/foam/u2/crunch/CapabilityFeatureView.js, src/foam/u2/view/ReadOnlyEnumView.js
=> Added border around enums with white backgrounds in table view

src/foam/u2/view/ScrollTableView.js, src/foam/u2/view/UnstyledTableView.js
ticket: https://nanopay.atlassian.net/browse/NP-3669
=> fixing result rendering

src/foam/u2/detail/SectionedDetailPropertyView.js
=> Fixed css bug for tableViews inside SectionedDetailView

src/foam/core/AbstractFObjectPropertyInfo.java
https://nanopay.atlassian.net/browse/NP-4024
=> check required on FObject validation

src/foam/u2/detail/SectionedDetailPropertyView.js
- Reverts changes to SectionedDetailPropertyView causing overflow bugs
- Adds new tooltip styling to properties on SectionedDetailPropertyView
=> Help icon placement fix

src/foam/u2/crunch/CrunchController.js, src/foam/u2/crunch/wizardflow/CreateWizardletsAgent.js, src/foam/u2/crunch/wizardflow/ShowPreexistingAgent.js
- fixes min max data not being saved upon reopening
- fixes showing the duplicate wizardlet bug
=> Np 3945/fix show preexisting agent

src/foam/u2/view/RadioView.js
- Added custom radio buttons
- changed "name" attribute for radio button inputs to better support voiceover applications
=> Fixed css inconsistency in RadioView

src/foam/u2/CheckBox.js, src/foam/u2/view/RadioView.js
- Made checkbox and radio button colours consistent
=> Check box and radio button colour change

src/foam/dao/AbstractF3FileJournal.js, src/foam/dao/WriteOnlyF3FileJournal.js
- https://nanopay.atlassian.net/browse/NP-4080
- Reset json formatter after finishing writing to journal
=> Fix NSpec json output

src/foam/i18n/pt_pt/locales.jrl
https://nanopay.atlassian.net/browse/NP-4073
=> payable's refresh message translation

src/files.js, src/foam/nanos/crunch/ui/UserCapabilityJunctionWAO.js, src/foam/u2/crunch/CrunchController.js, src/foam/u2/crunch/wizardflow/ConfigureFlowAgent.js, src/foam/u2/crunch/wizardflow/DetachAgent.js, src/foam/u2/wizard/BaseWizardlet.js
having git issues -same as -->  https://github.com/kgrgreer/foam3/pull/51
=> Detach wiz

src/foam/dao/Relationship.js, src/foam/nanos/menu/TreeAltView.js, src/menus
make treealtview relationship configurable
=> Treealtviewrelationship

src/foam/core/SubX.java
- https://nanopay.atlassian.net/browse/NP-3871
- https://github.com/kgrgreer/foam3/pull/23
- Fix missing services on SubX put since the delegate of SubX was abandoned when creating new SubX.
=> Fix SubX put

src/foam/u2/filter/properties/ReferenceFilterView.js
https://nanopay.atlassian.net/browse/NP-4092
=> fixing filter

src/foam/u2/FormattedTextField.js
- fix fontsize and vertical align
=> Formattedtextfieldcss

src/foam/nanos/iban/ValidationIBAN.js, src/foam/nanos/ruler/RulerData.js
- https://nanopay.atlassian.net/browse/NP-3794
- Add diff to ruler data to support test property change eg. `diff:iban` to check if the iban property has been changed
- Update min Iban length to accommodate SI bank
=> Add diff to ruler data

src/foam/i18n/pt_pt/locales.jrl, src/foam/nanos/approval/ApprovalRequest.js, src/foam/nanos/crunch/AgentCapabilityJunctionDAOSummaryView.js
Ref: https://nanopay.atlassian.net/browse/NP-4103
=> [NP-4103] - Add Portuguese translation to AgentCapabilityJunctionDAOSummaryView back button

src/files.js, src/foam/core/Fluent.js, src/foam/nanos/crunch/ui/CapabilityWizardlet.js, src/foam/u2/borders/CollapseBorder.js, src/foam/u2/crunch/CrunchController.js, src/foam/u2/crunch/wizardflow/CreateWizardletsAgent.js, src/foam/u2/crunch/wizardflow/DebugAgent.js, src/foam/u2/wizard/BaseWizardlet.js, src/foam/u2/wizard/NullWAO.js, src/foam/u2/wizard/ProxyWAO.js, src/foam/u2/wizard/internal/FObjectRecursionSlot.js, src/foam/u2/wizard/internal/PropertyUpdate.js, src/foam/util/async/Sequence.js
When the application mode is `DEVELOPMENT`, a debugging controller will display under each wizardlet. It shows any property updates that happen and provides buttons to manually save and load a wizardlet.
Also, this PR gives wizardlets and debugging tools the ability to decorate WAOs.
Future:
With this in place, it will be easy to add more features like "show in Crunch Lab", WAO events, etc.
=> [NP-4090] Debug tools for wizard

src/foam/mlang/mlang.js, src/foam/nanos/ruler/RulerData.js
- https://nanopay.atlassian.net/browse/NP-3794
- https://github.com/kgrgreer/foam3/pull/65
- Fix converting diff keys to string array
- Add java MQLExpr.toString()
=> Fix ruler data diff

src/foam/util/Emails/EmailsUtility.java
=> Revert "set the proper image logo"

src/files.js, src/foam/u2/view/RadioButton.js, src/foam/u2/view/RadioView.js
-Reduces the amount on googly eyes in radio buttons on extreme zoom levels
=> Fixes radio buttons

src/foam/core/AbstractMapPropertyInfo.java, src/foam/util/SafetyUtil.java
- https://nanopay.atlassian.net/browse/NP-3794
- Failed to compare map having array value eg. { arr: [1,2,3] }
- Support comparing array value in a map
=> Compare array value in map

src/foam/nanos/fs/fileDropZone/FileDropZone.js
https://nanopay.atlassian.net/browse/NP-4100
=> File drop zone RO support

src/foam/u2/wizard/ScrollingStepWizardView.js
=> Replaced action bar border with shadow

src/files.js, src/foam/u2/borders/LoadingBorder.js, src/foam/u2/wizard/ScrollingStepWizardView.js
=> [NP-3891] Add LoadingBoarder and apply it to wizardlets

src/foam/u2/ExportModal.js, src/foam/u2/ModalHeader.js, src/foam/u2/detail/SectionedDetailPropertyView.js, src/foam/u2/detail/SectionedDetailView.js, src/foam/u2/images/dropdown-icon.svg
Updated UI/UX for ExportModal according to logans design. You now have to select a data type before the modal will display details on exporting. Also tweaked some of the CSS.
Ticket: https://nanopay.atlassian.net/browse/NP-3990
Screenshots:
=> Updated UI/UX for ExportModal

src/files.js, src/foam/nanos/fs/fileDropZone/FileCard.js, src/foam/nanos/fs/fileDropZone/FileDropZone.js, src/foam/nanos/fs/fileDropZone/FilePreview.js, src/foam/u2/view/DocumentUploadView.js
- Added DocumentUploadView which fixes issues with document preview placement during file upload
- Cleaned up CSS to be more responsive in FilePreview, FileDropZone,  and FileCard
- Added Keyboard navigation to FileDropZone
=> Added DocumentUploadView | Accessibility improvements

src/foam/u2/FormattedTextField.js
add returnformatted option to formattedtextfield and fix a bug with removing a selectionrange from beginning of string
=> Formatted text field refactor

src/foam/box/SessionServerBox.java
- https://nanopay.atlassian.net/browse/NP-4173
- Fix sub context service override for skeleton service eg. brazilVerificationService
=> Fix sub context service override

src/foam/u2/FormattedTextField.js
=> Revert "Formatted text field refactor"

src/files.js, src/foam/u2/crunch/lab/CrunchLab.js, src/foam/u2/view/RichChoiceSummaryIdRowView.js, src/foam/u2/view/RichChoiceView.js
=> [NP-4185] Add a RichChoice RowView which shows data id along with summary

src/foam/nanos/fs/fileDropZone/FileDropZone.js, src/foam/u2/view/DocumentUploadView.js
Broke some things when I fixed upload on Friday. This fixes them.
=> Fixes css for some image dimensions in document upload (pdfs/large res)

src/foam/u2/view/RichChoiceView.js
https://nanopay.atlassian.net/browse/NP-4109
=> [NP-4109] Business Sectors selection needs to be local sorted

src/foam/u2/FormattedTextField.js
=> Revert "Revert "Formatted text field refactor""

src/foam/core/SubX.java
- https://nanopay.atlassian.net/browse/NP-4183
- Frozen subX put mutates the context
- Add fclone to SubX and fix SubX put immutability
=> Add fclone to SubX and fix SubX put immutability

src/foam/lib/formatter/JSONFObjectFormatter.java
JSONFObjectFormatter outputs nested FObject when storage transient is set
=> jsonfobjectformatter bug

src/foam/nanos/approval/ApprovalRequest.js, src/foam/u2/view/UnstyledTableView.js
and adding better fix
task https://nanopay.atlassian.net/browse/NP-4209
=> reverting my "fixes" for back button

src/foam/nanos/approval/ApprovalRequest.js
Failsafe for now, but looking into underlying problem with wrong context menu actions.
=> Added checks before popping on approval actions

src/foam/nanos/auth/CapabilityAuthService.js, src/foam/nanos/auth/ServiceProvider.js
fix issue where using xlocator cause NPEs when this method was called during user login before xlocator has been set
https://nanopay.atlassian.net/browse/NP-4241
=> NP-4241 fix context for serviceprovider.grantspermission

src/foam/nanos/auth/CapabilityAuthService.js, src/foam/nanos/auth/ServiceProvider.js
=> Revert "NP-4241 fix context for serviceprovider.grantspermission"

src/documentation/crunch-doc.flow, src/foam/nanos/crunch/UserCapabilityJunctionDAO.js, src/foam/nanos/crunch/UserCapabilityJunctionRefine.js, src/foam/nanos/crunch/doc.flow, src/foam/nanos/crunch/example/capabilities.jrl, src/foam/u2/crunch/CapabilityCardView.js, src/foam/u2/crunch/CapabilityFeatureView.js
=> Revert "Relevant Capability Id"

src/foam/u2/FormattedTextField.js, src/foam/u2/FragmentedTextField.js
allow backspacing on fragmentedtextfield textfields to go to the previous textfield when appropriate
=> fragmentedtextfield backspace

src/documentation/crunch-doc.flow, src/foam/nanos/crunch/UserCapabilityJunctionDAO.js, src/foam/nanos/crunch/UserCapabilityJunctionRefine.js, src/foam/nanos/crunch/doc.flow, src/foam/nanos/crunch/example/capabilities.jrl, src/foam/u2/crunch/CapabilityCardView.js, src/foam/u2/crunch/CapabilityFeatureView.js
=> Relevant Capability Id

src/foam/u2/view/ColumnConfigView.js
=> partial fix: fixing bug on updating search value onClose though

src/foam/nanos/approval/ApprovalRequest.js
NEW - with search filter - createdFor
OLD
=> searching on createdFor

src/foam/util/Emails/EmailsUtility.java
address: https://nanopay.atlassian.net/browse/NP-4217
nanoside: https://github.com/nanoPayinc/NANOPAY/pull/12516
=> add large logo for email

src/foam/nanos/crunch/UserCapabilityJunctionDAO.js
=> Revert "Np 4260/again"

src/foam/nanos/crunch/UserCapabilityJunctionDAO.js
=> Revert "[NP-4260] Change != to ( ! `.equals()` )"

src/documentation/crunch-doc.flow, src/foam/nanos/crunch/UserCapabilityJunctionDAO.js, src/foam/nanos/crunch/UserCapabilityJunctionRefine.js, src/foam/nanos/crunch/doc.flow, src/foam/nanos/crunch/example/capabilities.jrl, src/foam/u2/crunch/CapabilityCardView.js, src/foam/u2/crunch/CapabilityFeatureView.js
=> Revert "Revert "Relevant Capability Id""

src/foam/nanos/crunch/UserCapabilityJunctionDAO.js
=> Revert "Revert "[NP-4260] Change != to ( ! `.equals()` )""

src/foam/nanos/crunch/UserCapabilityJunctionDAO.js
=> Revert "Revert "Np 4260/again""

src/foam/comics/v2/DAOSummaryView.js
=> Load data foreach view rendering

src/foam/nanos/notification/email/EmailMessageValidationPropertyService.js, src/foam/nanos/notification/email/services.jrl, src/foam/util/Emails/EmailsUtility.java, tools/classes.js
https://nanopay.atlassian.net/browse/NP-4224
=> [NP-4224] Duplicate email some with missing subject

src/foam/core/types.js, src/foam/java/refinements.js, src/foam/u2/Element.js, src/foam/u2/view/TableCellFormatter.js
- Add FormattedString sub-type of String
- Override javasetter for FormattedString to strip the data of formatting
- Override tablecellformatter for FormattedString to apply format before adding the data
- Update CPF and CNPJ fields: https://github.com/nanoPayinc/NANOPAY/pull/12543
=> Cpfcnpjupdate2

src/foam/u2/detail/SectionView.js, src/foam/u2/detail/SectionedDetailPropertyView.js, src/foam/u2/wizard/ScrollingStepWizardView.js
- Fixed/Changed styling and spacing in the wizard to fix visual hierarchy changes caused by typography update
=> Updated wizard spacing and styling to work with new typography changes

src/foam/u2/LoadingSpinner.js, src/foam/u2/borders/LoadingBorder.js, src/foam/u2/crunch/wizardflow/SpinnerAgent.js, src/foam/u2/wizard/StepWizardletStepsView.js
- Removes modal background from spinner in post save loading
- Adds a size property to the spinner
- Fixed styling for spinner messages
- BONUS: spinner now works on Safari
=> Misc spinner css updates

src/foam/u2/crunch/wizardflow/SaveAllAgent.js
This PR adds exception handling and re-try to the SaveAll spinner that occurs after closing the wizard
=> [NP-4300] Fix SaveAll spinner for network failure

src/foam/u2/view/ScrollTableView.js, src/foam/u2/view/UnstyledTableView.js
Can't replicate locally and bug seems localized in my testing.
Issue on https://nanopay.atlassian.net/browse/NP-4313
These updates seem reasonable.
=> updates to ensure no null user obj being passed

src/foam/core/FObject.java, src/foam/dao/AbstractF3FileJournal.js, src/foam/dao/F3FileJournal.js
=> Revert "Move support for nested FObjects from F3FileJournal.merge into FObjec…"

src/foam/core/FObject.java
=> Revert "finally works"

src/foam/nanos/auth/ruler/PreventDuplicateEmailAction.js
- https://nanopay.atlassian.net/browse/NP-4280
- Fix prevent duplicate email to check the spid of the user who is submitting the request
=> Fix prevent duplicate email

src/foam/comics/v2/DAOUpdateView.js, src/foam/nanos/fs/fileDropZone/FileDropZone.js
Fixes issues caused by font update
=> Minor spacing fixes in FileDropZone and DAOUpdateView

src/foam/u2/detail/SectionedDetailPropertyView.js, src/foam/u2/tag/Select.js
-Fixes select view padding
-Moved select styling to Select.js from SectionedDetailPropertyView
=> Fixed select view padding

src/foam/nanos/crunch/lite/ruler/CapableCreateApprovalsRuleAction.js
Passes the FObject now instead of the capableObj.
=> Change arg to use FObject

src/foam/nanos/auth/Address.js
fix for issue : no server side validation for Address.REGION - ucjs with address data can be granted without providing region
=> add java validation for address.region

src/foam/nanos/approval/ApprovalStatus.js, src/foam/nanos/controller/ApplicationController.js, src/foam/u2/view/ReadOnlyEnumView.js
- Added a function that lets you unwrap CSS macros in individual views
- Fixed colour rendering for enums
=> Fixed enum color rendering

src/documentation/crunch-doc.flow, src/documentation/intro-to-flow.flow, src/foam/flow/widgets/doc.flow, src/foam/foamlink/doc.flow, src/foam/nanos/alarming/Alarm.flow, src/foam/nanos/crunch/doc.flow, src/foam/nanos/crunch/lite/doc.flow, src/foam/nanos/medusa/Medusa.flow, src/foam/u2/svg/map2d/doc.flow, src/foam/u2/wizard/doc.flow
- Updated flow docs to match new typography styling
=> Flow docs update

src/foam/u2/view/UserPropertyAvailabilityView.js
Fixes alignment for checkmark on "Create an Account" screen
New: 
Old:
=> Fixed checkmark alignment on signup screen

src/foam/u2/view/UnstyledTableView.js
PS: Not sure what these style css lines do as they have no effect on the scroll table views I tested
=> Fixes rendering for tables not using ScrollTableVIew

src/foam/core/Property.js, src/foam/flow/DocumentMenu.js, src/foam/nanos/boot/DAONSpecMenu.js, src/foam/nanos/client/ClientBuilder.js, src/foam/nanos/controller/ApplicationController.js
remove async factory warnings for those factories that should return promises
Address : https://nanopay.atlassian.net/browse/NP-4342
=> NP4342 / cleanup async factory warnings 

src/files.js, src/foam/flow/widgets/SequenceSummary.js, src/foam/flow/widgets/TryItSnippet.js, src/foam/u2/ViewSpec.js, src/foam/u2/crunch/CrunchController.js, src/foam/u2/crunch/doc.flow, src/foam/u2/crunch/wizardflow/CheckPendingAgent.js, src/foam/u2/crunch/wizardflow/CheckRootIdAgent.js, src/foam/u2/crunch/wizardflow/ConfigureFlowAgent.js, src/foam/u2/crunch/wizardflow/CreateWizardletsAgent.js, src/foam/u2/crunch/wizardflow/DebugAgent.js, src/foam/u2/crunch/wizardflow/DetachAgent.js, src/foam/u2/crunch/wizardflow/FilterGrantModeAgent.js, src/foam/u2/crunch/wizardflow/LoadCapabilitiesAgent.js, src/foam/u2/crunch/wizardflow/LoadTopConfig.js, src/foam/u2/crunch/wizardflow/RequirementsPreviewAgent.js, src/foam/u2/crunch/wizardflow/SpinnerAgent.js, src/foam/u2/crunch/wizardflow/StepWizardAgent.js, src/foam/u2/crunch/wizardflow/lite/MaybeDAOPutAgent.js, src/foam/u2/svg/graph/DAGView.js, src/foam/util/async/Sequence.js, src/foam/util/async/doc.flow
Added in this PR
- A FLOW widget specifically for methods returning sequences
- Documentation for `foam.util.async.Sequence`
- Documentation for sequences used in CRUNCH
- Documentation properties on context agents used in CRUNCH
=> [NP-4324] Document wizard sequences

src/foam/comics/DAOControllerView.js, src/foam/comics/DAOCreateController.js, src/foam/comics/DAOCreateControllerView.js, src/foam/comics/v2/DAOBrowseControllerView.js, src/foam/comics/v2/DAOBrowserView.js, src/foam/comics/v2/DAOCreateView.js, src/foam/comics/v2/DAOSummaryView.js, src/foam/comics/v2/DAOUpdateView.js, src/foam/core/Action.js, src/foam/nanos/auth/LanguageChoiceView.js, src/foam/nanos/u2/navigation/SignIn.js, src/foam/nanos/u2/navigation/SignUp.js, src/foam/u2/ActionView.js, src/foam/u2/crunch/CapabilityRequirementView.js, src/foam/u2/wizard/ScrollingStepWizardView.js
- Updated default actionView to secondary 
- Updated styling for Export/Import/Refresh buttons in DAOBrowser view
- Added the option to specify button style in the action definition 
- Fixed a css bug in destructive buttons
- Fixed css bug in CONFIRM buttons 
- Updated actions to match default ActionView changes [Part 1/n]
=> Updated default actionView to secondary 

src/foam/i18n/pt_pt/locales.jrl, src/foam/nanos/approval/ApprovalRequest.js, src/foam/nanos/ticket/Ticket.js
Adding assign actions consistent with  ApprovalRequest assign
Also merge approvalRequest messages.
=> Np 4335/add assign methods to ticket

src/foam/comics/DAOControllerView.js, src/foam/comics/DAOCreateController.js, src/foam/comics/DAOCreateControllerView.js, src/foam/comics/v2/DAOBrowseControllerView.js, src/foam/comics/v2/DAOBrowserView.js, src/foam/comics/v2/DAOCreateView.js, src/foam/comics/v2/DAOSummaryView.js, src/foam/comics/v2/DAOUpdateView.js, src/foam/core/Action.js, src/foam/nanos/auth/LanguageChoiceView.js, src/foam/nanos/u2/navigation/SignIn.js, src/foam/nanos/u2/navigation/SignUp.js, src/foam/u2/ActionView.js, src/foam/u2/crunch/CapabilityRequirementView.js, src/foam/u2/wizard/ScrollingStepWizardView.js
=> Revert "Updated default actionView to secondary "

src/foam/comics/v2/DAOSummaryView.js
SO git versioning is failing at showing my changes. The image shows what I did better.
The issue was when Hassen was testing - he found the data was loaded after the screen loaded. 
Can't garantee this works, but does not seem to cause previous issues with async conversion (https://github.com/kgrgreer/foam3/pull/185)
=> put the object update from dao in the slot for data - daoSummaryView

src/foam/comics/v2/DAOSummaryView.js
Reverts kgrgreer/foam3#261
didn't do what it was intended. Seems to not work - safer to remove until issue is actually located
=> Revert "put the object update from dao in the slot for data - daoSummaryView"

src/foam/nanos/controller/ApplicationController.js
address: https://nanopay.atlassian.net/browse/NP-4338
=> use copyFrom to overwrite the appConfig

src/foam/core/types.js
https://nanopay.atlassian.net/browse/NP-4398
=> NP-4398 / Hide formatted prop

src/foam/nanos/servlet/VirtualHostRoutingServlet.js
nanopay: https://github.com/nanoPayinc/NANOPAY/pull/12679
=> add html2PDF lib

src/foam/u2/dialog/NotificationMessage.js
- Temporarily increase max notification width
- CSS cleanup
=> Temporarily increase the notification width

src/foam/nanos/alarming/Alarm.js
Added constructor to alarm for name and note
=> Alarm constructor name & note

src/documentation/crunch-doc.flow, src/documentation/intro-to-flow.flow, src/foam/flow/widgets/doc.flow, src/foam/foamlink/doc.flow, src/foam/nanos/alarming/Alarm.flow, src/foam/nanos/crunch/doc.flow, src/foam/nanos/crunch/lite/doc.flow, src/foam/nanos/medusa/Medusa.flow, src/foam/u2/svg/map2d/doc.flow, src/foam/u2/wizard/doc.flow
Reverts kgrgreer/foam3#240
Revert due to new typography changes
=> Revert "Flow docs update"

src/foam/u2/view/MultiChoiceView.js
=> sort MinMax choices in MultiChoiceView

src/foam/nanos/crunch/lite/ruler/UCJApprovableValidateAction.js, src/foam/nanos/crunch/lite/rules.jrl, src/foam/nanos/nanos.js, tools/classes.js
Added a rule which will call validate on UCJ related Approvables then update the diff on the approvable accordingly
=> Added UCJApprovableValidateAction

src/foam/nanos/alarming/Alarm.js
Added another constructor Alarm(String name, String note, foam.log.LogLevel severity)
=> Alarm Constructor (name, note, severity)

src/foam/nanos/servlet/VirtualHostRoutingServlet.js
address: https://nanopay.atlassian.net/browse/NP-4446
error from missing library on production
=> [NP-4446] add html2pdf lib on production

src/foam/u2/borders/SplitScreenBorder.js, src/foam/u2/view/LoginView.js
- Cleaned up code in LoginView that fixes DOM order
- Cleaned up CSS
=> Fixed layout in LoginView and cleaned up CSS

src/foam/u2/ActionView.js, src/foam/u2/view/RichChoiceView.js
Ticket: https://nanopay.atlassian.net/browse/NP-4450
=> Fixed RichChoiceView spacing and 'confirm' ActionView

src/foam/u2/ExportModal.js
=> Removed empty export driver element from the view

src/foam/nanos/approval/ApprovalRequest.js
Diff shows alot of changes but its because I moved createdFor to come after created and before createdBy. So that the order can make sense too.
=> Fix detail view columns for ApprovalRequest

src/foam/nanos/notification/NotificationMessageModal.js
add a new line at new line character
**before**
**after**
=> Notification message style update

src/foam/nanos/ruler/RuleGroup.js, src/foam/nanos/ruler/RulerDAO.js, src/ruleGroups, src/services
- https://nanopay.atlassian.net/browse/NP-2648
- https://nanopay.atlassian.net/browse/NP-3382
- Add rule group priority and support
- Configure spidCapability rule group priority
- Cleanup rule SPID enforcement as it was replaced by permissioned rule
=> Add rule group priority and support

src/foam/u2/IFrameHTMLView.js
https://nanopay.atlassian.net/browse/NP-4458
=> prevent iframe overflowing on smaller windows

src/foam/nanos/client/ClientBuilder.js
Applied a patch from @lchanmann to fix spid-specific services
=> Applied chanmann's patch to fix spid-specific services

src/foam/comics/v2/DAOSummaryView.js, src/foam/nanos/theme/ThemeGlyphs.js, src/foam/net/web/HTTPRequest.js, src/foam/u2/ActionView.js, src/foam/u2/ButtonSize.js
- Added support to use themeGlyphs in ActionViews
- SVGs used for button icons are loaded inline
- Added role attribute to button icons to improve accessibility 
- Fixed a bug with HTTP Request when using relative paths
- Added/Cleaned up some themeGlyphs
=> Added inline SVGs to actionView

src/foam/nanos/notification/email/DAOResourceLoader.java, src/foam/nanos/notification/email/EmailTemplateEngine.js
* find emailt template via DAOResourceLoader rather than emailTemplateDAO
=> find emailtemplate from dao

src/foam/u2/ExportModal.js
ticket: https://nanopay.atlassian.net/browse/NP-4499
=> NP-4499 Googlesheet export UI wizard is broken

src/foam/nanos/alarming/Alarm.js
- https://nanopay.atlassian.net/browse/NP-4231
- Add permissions for start and stop alarm actions
=> Add permissions for start and stop alarm actions

src/foam/u2/view/TitledArrayView.js
https://nanopay.atlassian.net/browse/NP-4451
=> [DO_NOT_MERGE] [NP-4451] Beneficial owner title needs to be translated

src/foam/nanos/auth/CreateUserCapabilityJunctionOnSpidSet.js, src/foam/nanos/auth/SetUserServiceProviderJunctionRuleAction.js
@noodlemoodle .. looks like this rule wasn't working again. I didn't change anything, but just redeployed with the debugging messages and it worked again. It seems like the rule engine didn't load the rules the first time, though I didn't see any errors. I'm adding these debug messages to help track the running of these actions in the future.
=> Adding debugging to rules that are sometimes not being triggered

src/foam/nanos/nanos.js, src/foam/nanos/ruler/StopRulerAction.js, tools/classes.js
- https://nanopay.atlassian.net/browse/NP-4553
- Add StopRulerAction (needed for user-allow-duplicate-email-rule)
=> Add StopRulerAction

src/foam/nanos/approval/ApprovalRequest.js, src/foam/nanos/approval/SendGroupRequestApprovalDAO.js, src/foam/nanos/crunch/lite/ruler/CapableCreateApprovalsRuleAction.js
Added a optional additionalGroups array to specify on an approval request.
=> Np 4582/multiple approval groups foam

src/foam/nanos/pm/PMTableView.js
This reverts commit 94f40ac25b4005493d78a8deacd297d6eee87d8a.
=> Revert "Switched PMTableView to extend ScrollTableView."

src/foam/nanos/ticket/Ticket.js, src/foam/nanos/ticket/services.jrl
=> Revert "Np 4592/long to string"

src/foam/nanos/ticket/Ticket.js, src/foam/nanos/ticket/services.jrl
=> Np 4592/long to string

src/foam/nanos/controller/ApplicationController.js, src/foam/u2/view/TreeView.js
- Fixed a bug where returnExpandedCSS would return original value
- Fixed TreeView icons to use theme colour
=> Fixed bug with returnExpandedCSS function and treeview selected colour

src/foam/u2/filter/FilterView.js
=> Removes redundant filter text

src/files.js, src/foam/comics/v2/DAOBrowserView.js, src/foam/i18n/pt_pt/locales.jrl, src/foam/nanos/boot/DAOConfigSummaryView.js, src/foam/nanos/images/ic-search.svg, src/foam/nanos/menu/VerticalMenu.js, src/foam/u2/SearchField.js, src/foam/u2/filter/FilterView.js, src/foam/u2/filter/advanced/CriteriaView.js, src/foam/u2/images/ic-search.svg, src/foam/u2/search/TextSearchView.js, src/foam/u2/view/ColumnConfigView.js, src/foam/u2/view/ReciprocalSearch.js, src/foam/u2/view/SimpleSearch.js, src/foam/u2/wizard/IncrementalStepWizardView.js, src/foam/u2/wizard/ScrollingStepWizardView.js, src/foam/u2/wizard/StepWizardletStepsView.js
- Added a searchField with default type,icon and placeholder
- Moved Wizard search to right side and replaced with SearchField
- Replaced Input in TextSearchView to SearchField
- Updated Search icon
- Updated old search fields to use SearchField instead of Input
=> Added SearchField

src/foam/nanos/approval/FulfilledCompositeApprovableRule.js, src/foam/nanos/auth/ServiceProvider.js, src/foam/nanos/crunch/CrunchService.js, src/foam/nanos/crunch/ServerCrunchService.java, src/foam/nanos/crunch/lite/rules.jrl, src/foam/nanos/crunch/permissions.jrl, src/foam/nanos/crunch/ruler/ConfigureUCJExpiryOnGranted.js, src/foam/nanos/crunch/ruler/SaveUCJDataOnGranted.js, src/foam/nanos/crunch/scripts.jrl, src/foam/nanos/crunch/services.jrl, src/foam/nanos/crunch/ui/ApprovableUserCapabilityJunctionWAO.js, src/foam/nanos/nanos.js, src/foam/u2/crunch/wizardflow/ApprovalRequestAgent.js, src/foam/u2/crunch/wizardflow/LoadCapabilitiesAgent.js, tools/classes.js
=> Revert "[NP-4392] Add approvable generation for updates on granted UCJs"

src/foam/demos/examples/FBE.js, src/foam/graphics/CView.js, src/foam/u2/Element.js, src/foam/u2/FormattedTextField.js, src/foam/u2/FragmentedTextField.js, src/foam/u2/PopupView.js, src/foam/u2/Scroller.js, src/foam/u2/TableView.js, src/foam/u2/Tooltip.js, src/foam/u2/crunch/CapabilityStore.js, src/foam/u2/md/OverlayDropdown.js, src/foam/u2/property/MDPopup.js, src/foam/u2/property/MDSelect.js, src/foam/u2/property/MenuElement.js, src/foam/u2/tag/Select.js, src/foam/u2/view/FileUploadTextField.js, src/foam/u2/view/RichChoiceView.js, src/foam/u2/view/ScrollDAOView.js, src/foam/u2/view/ScrollTableView.js, src/foam/u2/wizard/ScrollingStepWizardView.js, src/foam/u2/wizard/StepWizardletStepsView.js, src/org/chartjs/AbstractChartView.js
address:
https://nanopay.atlassian.net/browse/NP-4341
=> NP4341 / change the el function in Element to be promise

src/foam/nanos/approval/FulfilledCompositeApprovableRule.js, src/foam/nanos/auth/ServiceProvider.js, src/foam/nanos/crunch/CrunchService.js, src/foam/nanos/crunch/ServerCrunchService.java, src/foam/nanos/crunch/lite/rules.jrl, src/foam/nanos/crunch/permissions.jrl, src/foam/nanos/crunch/ruler/ConfigureUCJExpiryOnGranted.js, src/foam/nanos/crunch/ruler/SaveUCJDataOnGranted.js, src/foam/nanos/crunch/scripts.jrl, src/foam/nanos/crunch/services.jrl, src/foam/nanos/crunch/ui/ApprovableUserCapabilityJunctionWAO.js, src/foam/nanos/nanos.js, src/foam/u2/crunch/wizardflow/ApprovalRequestAgent.js, src/foam/u2/crunch/wizardflow/LoadCapabilitiesAgent.js, tools/classes.js
=> Revert "Revert "[NP-4392] Add approvable generation for updates on granted UCJs""

src/foam/u2/view/UnstyledTableView.js
Ticket: https://nanopay.atlassian.net/browse/NP-4647
Old: 
New:
=> Changed flex grow for table columns with unset width for better spacing

src/foam/u2/wizard/ScrollingStepWizardView.js
Button tag only applies styling to label when it is of class 'String' hence the change
=> Fixed font weight bug with wizard save button

src/foam/nanos/theme/ThemeGlyphs.js, src/foam/u2/dialog/NotificationMessage.js
Ticket: https://nanopay.atlassian.net/browse/NP-4661
Image background when set in CSS was not a part of the button. Also added close as a theme icon.
=> Notification close button fix
