kgrgreer/foam3

src/foam/core/AbstractFObjectPropertyInfo.java

- https://github.com/foam-framework/foam2/pull/5108
- Add null check before validate call on the FObject.

Fix FObject property validation - Add null check

---

src/foam/core/SubX.java
src/foam/nanos/session/Session.js

- https://nanopay.atlassian.net/browse/NP-3871
- https://github.com/foam-framework/foam2/pull/5037
- bepay user cannot login due to 'bepay' subX is frozen and discards subsequent mutation
- Create new subX when calling put/putFactory on a frozen subX to support session with hierarchical SPID context

Fix hierarchical spid context

---

src/foam/u2/detail/SectionedDetailPropertyView.js

Fixes Table view without breaking(i think...tested the parts it broke before) other parts of SectionedDetailPropertyView
Old: 
Fixed:

Fixed CSS bug for tableViews inside SectionedDetailView

---

src/foam/nanos/auth/SystemAuthService.js

System auth service now applies short cut if context group applies "*" (All access) permission. 
This by passes the authorization check delegate cascade improving performance, avoiding unnecessary logic and allows for refined permission checks inside of other system authorization logic.

System auth service update

---

src/foam/u2/view/TabChoiceView.js

That way the tab choice view is generic enough to be used without needing knowledge of translations + locales

Make tab choice view not require translations by passing a default parameter

---

src/foam/box/SessionServerBox.java

Revert clusterable=true when session not found. It was intended to allow admin to login before medusa replay was complete, but it allows all users to login.

[NP-4072] SessionServerBox

---

src/foam/nanos/boot/NSpecFactory.java

- https://nanopay.atlassian.net/browse/NP-3871
- https://github.com/kgrgreer/foam3/pull/23
- The context of services created in a sub context cannot access to services in parent/root
- Use x_ instead of the delegate since the delegate of a sub context only contains services add to the sub context

Fix context for service created in sub context

---

src/foam/util/Emails/EmailsUtility.java

https://nanopay.atlassian.net/browse/NP-3685
fixed broken image logo in email templates 
old : 
new :

set the proper image logo

---

src/foam/u2/crunch/wizardflow/DebugAgent.js

Would break when you select only one option in the min max with debug mode on.
To be done instead of invisible wizardlets because a wizardlet could be invisible just because it wasn't selected in a min-max. Therefore we wouldn't see the crunch debugger appear in sections which derive from a min max choice. Would also break canGoNext on single choices.

Changed debugAgent to filter out off-less wizardlets

---

src/foam/u2/view/RichChoiceView.js

Placeholders were not being displayed because the arguments passed to the translation method were incorrect. But I found there was no need to translate texts that had already been translated, so I simply removed  the translation part to fix the issue.
**Owner**
**Business sector**

[NP-3972] fix richChoiceView placeholder

---

src/foam/core/SubX.java

- https://nanopay.atlassian.net/browse/NP-4183
- bepayX.get("group") was reset to null when applying session but on the next call of bepayX.get("group") it returns `system` group instead of null because it propagates the lookup to the parent context.
- Keep track of services added to subX and prevent propagating to parent context (for null override)
- Add rm method to SubX for removing the service from the subX

Fix subX leaking system group

---

src/foam/u2/wizard/BaseWizardlet.js

Since capabilities have a `wizardlet` property to specify a different wizardlet from the default, any imports requiring a wizard context will sometimes produce an error.
This PR makes one such import optional, and logs an error if it doesn't exist when it should.

[NP-4094] Make a wizard context import on wizardlet optional

---

src/foam/u2/wizard/ScrollingStepWizardView.js

Minor fix to section header alignment
Before: 
After:

Align section headers

---

src/documentation/crunch-doc.flow
src/foam/nanos/bench/BenchmarkRunner.java
src/foam/nanos/crunch/UserCapabilityJunctionDAO.js
src/foam/nanos/crunch/UserCapabilityJunctionRefine.js
src/foam/nanos/crunch/doc.flow
src/foam/nanos/crunch/example/capabilities.jrl
src/foam/u2/crunch/CapabilityCardView.js
src/foam/u2/crunch/CapabilityFeatureView.js

Update references to arbitrary alphanumeric capability ids with relevant strings that describe the capability and allows  updating user capability junction target ids if permitted.
Current references to capabilities are for logging purposes: **_"logs for a bug where sometimes signing officer address isn’t saved properly but its impossible to reproduce so the logs are there in case it happens again"_**
Removed references to project specific capability ids since they're no longer required with the flow they relate to.

Relevant Capability Id

---

src/foam/u2/ActionView.js
src/foam/u2/md/OverlayDropdown.js
src/foam/u2/view/ColumnConfigView.js
src/foam/u2/view/EditColumnsView.js
src/foam/u2/view/OverlayActionListView.js

- Updated styling for table edit menu and context menu
- Drop-downs in edit menu no longer select the parent element when clicked
- Added Css to unstyled buttons to override browser styling
Edit menu: 
Context Menu:

Updates visual styling for table edit and context menus

---

src/foam/u2/view/RichChoiceView.js

https://nanopay.atlassian.net/browse/NP-4229
fixed obj value translation bug on rich choice view. placeholder and selected value translation look fine.
previous related PR : https://github.com/kgrgreer/foam3/pull/96

obj value translation in richChoiceView

---

src/foam/u2/view/UnstyledTableView.js

Previously, if actions were overwritten by a subclass after the merger, those overwritten actions would remain and so following instances would inherit actions they shouldn't have in the context menu.
Also use `getAxiomsByClass` instead of `getOwnAxiomsByClass` so that we just collect the actions from the class each time. Now that we reset the actions at the end of each iteration to use the actions in the  `of` property + `contextMenuActions` actions, we shouldn't have merger conflicts.
Example of bug: If `entryA` is `NatureCodeApprovalRequest` and entry B is `ComplianceApprovalRequest`. `entryB` comes after `entryA` in the dao table. B is not a subclass of A. `entryA` overrides the approve method. When both `entryA` and `entryB` are in the table in the order of AB, in the context menu …

Made actions reset after every table entry

---

src/foam/nanos/auth/CapabilityAuthService.js

Test for cap before setting context. 
Also report warning when UCJ is granted but target id cannot be found

NP-4241 CapabilityAuthService NPE 

---

src/foam/i18n/pt_pt/locales.jrl
src/foam/nanos/crunch/ui/UserCapabilityJunctionWAO.js
src/foam/nanos/theme/ThemeGlyphs.js
src/foam/u2/wizard/BaseWizardlet.js
src/foam/u2/wizard/ScrollingStepWizardView.js
src/foam/u2/wizard/StepWizardController.js
src/foam/u2/wizard/StepWizardletStepsView.js
src/foam/u2/wizard/WizardletIndicator.js

Failures on a DAO put leads to a wizardlet being stuck in `loading` state, preventing any further saves or loads.
This PR adds a more controlled failure mode for wizardlets and the wizard. Any exception during save and load will be reported as a network error and begin a re-try interval. The wizard will display a sticky banner, and will also not allow the user to click the primary action of the wizard ("done"/"save"/"submit")

[NP-4300] Handle network failures in wizard

---

src/foam/nanos/doc/DocumentationView.js

Fixes api menus that set docKey manually from getting overwritten to ""

Support hard set docKey values

---

src/documentation/crunch-doc.flow
src/files.js
src/foam/flow/widgets/AxiomShortSummary.js
src/foam/flow/widgets/ModelSummary.js
src/foam/flow/widgets/TabbedModelDocumentation.js
src/foam/u2/wizard/BaseWizardlet.js
src/foam/u2/wizard/StepWizardConfig.js
src/foam/u2/wizard/StepWizardController.js
src/foam/u2/wizard/Wizardlet.js
src/foam/u2/wizard/WizardletSection.js
src/foam/u2/wizard/doc.flow

This is the first part of wizard documentation: documentation for the wizard itself, not considering its use in CRUNCH.
The next part will be a separate FLOW doc in `foam.u2.crunch` documenting CrunchController.

[NP-4324] Add wizard documentation

---

src/foam/u2/view/ScrollTableView.js

**so the bug cause was:**
we render pages on table_ being set
then refresh called on `updateCount` and all the pages got deleted and added again

fixing rendering pages twice on count updated and on table_ set

---

src/foam/nanos/theme/Themes.js

When a group specifies a defaultMenu, it should overwrite the theme's defaultMenu as well as logoRedirect props.

Overwrite logoRedirect with group defaultMenu

---

src/foam/core/Enum.js
src/foam/nanos/approval/ApprovalRequest.js
src/foam/u2/view/ReadOnlyEnumView.js

- Any enums without a colour/background property for at least one of it's values now uses a non-pill view
- Removed custom enum view from Approval Request
New: 
Old: 
Thanks Eric :)

Added a fancy and non-fancy enum view

---

src/foam/comics/v2/DAOBrowserView.js

Moved padding to the DAOBrowserView rather than ScrollTableView to improve compatibility with custom DAOBrowserViews

Fixed css bug for tables using custom DAOBrowserView

---

src/foam/core/ImportsExports.js

In the UCJ's case, the first call to `Object.defineProperty`  for **slotName** (https://github.com/kgrgreer/foam3/compare/development...tharmaman:NP-4493/HandleErrorsForImports?expand=1#diff-a538e25b7c753f2560a26b233b0c69ada59758c23dd8ff7043c0f5904f953c18L109) throws a TypeError (see 3 below). Setting Configurable: true when calling Object.defineProperty for Imports  fixes  this.
More Details:
1. For UCJ, the first axiom to get processed in `FObject.installAxioms` is the **CapabilityJunctionPayload MixIn**. Within the CapabilityJunctionPayload class, it **imports the capabilityDAO**. After processing the MixIn, the UCJ class has now has `capabilityDAO$` available as a property.
2. Shortly after the MixIn, the **direct capabilityDAO import** on UCJRefine gets processed in …

Set Configurable: true when calling Object.defineProperty for Imports

---

src/foam/nanos/crunch/CapabilityUpdateInterceptDAO.java

strange that private constructors seem to work fine in scripts half of the time :thinking:

Made CapabilityUpdateInterceptDAO constructor public

---

src/foam/nanos/crunch/UCJProperty.js

So this is an error because the e is undefined in https://github.com/kgrgreer/foam3/compare/development...kgrgreer:NP-4517/FixUCJProperty?expand=1#diff-4d259c7ceedb70c5dc712f1e4b55088c80f5ad1d599571f5376881f669be51ffR41. 
For some reason this would break invoices when running medusa. Despite not being used. Investigating on the why.

Move e to the  top

---

src/foam/nanos/medusa/MedusaConsensusDAO.js

When copying storageTransient properties, test isSet so only updates are copied.
Previously was blindly copying so all storageTransient properties, including those with default values, were being copied, so values were being reset to default.

[NP-4445] MedusaStorageTransientIsSet

---

src/foam/comics/v2/DAOCreateView.js
src/foam/comics/v2/DAOUpdateView.js
src/foam/nanos/auth/RetrievePassword.js
src/foam/nanos/notification/NotificationSettingsView.js
src/foam/nanos/u2/navigation/SignIn.js
src/foam/nanos/u2/navigation/SignUp.js

Presently directly calling 
this.ctrl.notify of  this.notify which generates a transient Notification is not working.  Have to use this NotificationMessage class which is very puzzling. 
* Wish to remove use of NotificationMessage, relying solely on Notifcation.transient for toast notifications.
* Parse/split service side exceptions into title and message for toast notifications.
* Provide translation via   exception-package.exception-name.title and exception-package.exception-name.message

[NP-3799] ClientRuntimeException toast title/message and translation

---

src/foam/nanos/crunch/predicate/CapabilityIsStatus.js
src/foam/nanos/nanos.js
tools/classes.js

Addresses: https://nanopay.atlassian.net/browse/NP-4618
CapabilityGranted is a predicate used in a few capability predicate areas that grab the user's user capability junction in reference to the predicates capability Id. This is useful for checking if a user capability junction is status in a GRANTED state other than the user capability junction iterating through whatever process the predicate is being applied to. However the predicate is limited to the GRANTED Status. The status should be configurable.
Removed CapabilityGranted since it would have solely been used as a reference to existing journals. Updates on these journal entries can be made to avoid redundant classes.

CapabilityIsStatus

---

src/foam/nanos/crunch/predicate/CapabilityIsStatus.js
src/foam/u2/wizard/ScrollingStepWizardView.js

Fixes a recursion that leads to a freezing browser if scrolling wizard element offsetparent is null
Also updated typo in documentation on CapabilityIsStatus.

Fix recursive warning scroll wizard

---

src/foam/core/FOAMException.js
src/foam/nanos/auth/LocaleSupport.js
src/foam/nanos/controller/ApplicationController.js
src/foam/nanos/session/Session.js
src/foam/nanos/theme/Theme.js

Remove default language from Theme, and fall back to default provided by LocalSupport.
LocaleSupport test for user, then Theme language if set, then HTTP headers for browser supplied language. 
Used for Server side Exception Translation.
Future work will attempt to translate client side.

NP-3799 LocaleSupport 
